
name: Build docker images

on: [push, pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: |
          indigoiam/openresty-voms
        tags: |
          type=sha
          type=semver,pattern={{raw}}
          type=ref,event=branch

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build & Push image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
